### ISSUE TITLE
dark theme disabled while envify is running

### ISSUE THREAD

**Issue by reiny2000** [ylecuyer/envify#20] opened 2018-07-07 12:40 UTC
up until 63.0a1 07.07.2018 the dark theme would disappear at the top of the page (in the bookmarks area and where the tabs are located). that's where the extension modifies the browser's colours and i don't see why it now treats it as a whole, canceling the dark theme entirely.

**Comment by Smile4ever** [comment] 2018-07-07 18:15
Duplicate of https://github.com/ylecuyer/envify/issues/7

**Closed as completed** 2018-07-29 15:00 UTC
Labels: duplicate, bugzilla
