### ISSUE TITLE
Environments disappeared

### ISSUE THREAD

**Issue by breggles** [ylecuyer/envify#21] opened 2019-08-19 10:00 UTC
Started up FF this morning, the envify options tab loaded by itself (it does that sometimes) and all my environments were gone (that's the first time it's done that). I last ran FF last Friday and I'm pretty sure the environments were fine, then.

**Comment by ylecuyer** [comment] 2019-08-19 18:18
I pushed an update at the beginning of the month. It may be related. Did you update the addon recently?
The configuration can be synced too. Did you change the account you use with Firefox recently?

**Comment by breggles** [comment] 2019-08-20 09:00
The add-on is set to auto-update. It says:

> Version 0.3
> Last Updated July 29, 2019

So I don't think the update did it.
I haven't changed my account and I'm still logged in to my account. I don't sync add-ons because i use different add-ons on different machines. Or is it syncing options what does it?

**Comment by ludsoft** [comment] 2019-08-21 12:02
First, thanks a lot for the add-on! It's really usefull and really well done.
I've got the same issue with the environments that disappeared for the second time in a month. I'm using firefox on Ubuntu.
It seems that it happens when firefox is updated using the usual ubuntu update system. 
Same as @breggles the last update of envify is July 29.
I do not sync add-ons either. 
I'm sure I had firefox updated in the past without any issue. 
Let me know if any additional info would be helpful. 

Is there a way for me to make a local backup of the environment list and to restore it when it happens?

**Comment by breggles** [comment] 2019-08-21 13:48
For what it's worth, i'm using FF in Windows 10.

**Comment by garrettw** [comment] 2019-09-04 14:54
Same problem here. I'm on Firefox Developer Edition on macOS Mojave and I just updated Firefox and lost all of my envify settings. Super unhappy about this because I had several and didn't have them saved anywhere (didn't think I needed to).

**Comment by arnaud-jacquemin** [comment] 2019-09-16 08:36
Same problem here, for the second time in less than a month.
I'm currently using Firefox 69.0, installed on the 9th of September. I can't remember if the problem occurred that day.
I can send the `about:support` report if it helps.

**Comment by ylecuyer** [comment] 2019-09-17 16:22
I still haven't found the root cause of this error.

I'll add an export/import settings so you all can save you configuration externally and import it if this is to occur again. This will help with the frustration while we find the root cause.

**Comment by ylecuyer** [comment] 2019-09-17 22:16
Here is the PR https://github.com/ylecuyer/envify/pull/22
Please have a look at it, I'll merge it by the end of the week (23/09/2019) and publish a new version of the extension if it is OK for everyone

**Comment by ludsoft** [comment] 2019-09-18 11:24
Looking at PR #22 that would work for me to save the configuration and re import it.  
To add on the mystery, I don't think I lost the my environments while upgrading to FF69. 
Thanks a lot for PR #22.

**Comment by FlyveHest** [comment] 2019-11-08 07:26
Just restarted FF due to an update this morning, and this happened to me as well (Now running FF 70 and 0.4 of the extension)

The Envify configuration screen popped up, and it was empty, could it be related to an update to FF that somehow removes all your settings?

**Comment by FlyveHest** [comment] 2019-11-08 07:34
That very much seems to be the case, because I just got an update to 70.1, restarted, and all my configures environments were gone.

**Comment by FlyveHest** [comment] 2019-12-09 07:28
Just updated to 71, and all environments gone again.

**Comment by ylecuyer** [comment] 2019-12-14 23:29
Thanks for your report. I hope you had your configuration saved and you were able to restore it after that :(

I still have to do some experiments with FF upgrades to pin point the root of all those troubles

**Comment by ludsoft** [comment] 2020-01-18 23:18
It happened to me again with the upgrade to 72 (as it did with several others upgrade) and it never happens outside of FF update. A non issue as my environments are saved so it's a 5 second job to have everything running again. I think I've read somewhere that firefox is increasing the number of releases to monthly, will have to spend 5 seconds more often then :-).

**Comment by FlyveHest** [comment] 2020-01-19 09:07
And it is probably a bigger issue for users that haven't saved their setup and/or have found this issue so they know what to do.

**Comment by ajoah** [comment] 2020-01-19 09:35
Hi @ylecuyer 

I have never developed a firefox extension but anyway i have looked at the code : 

https://github.com/ylecuyer/envify/blob/6a7a3c53c0c0c142cc1d790f5e61b67180bc19f4/background.js#L27-L41

The documentation gives the possible values of `reason` : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/OnInstalledReason

Don't you think that when there is a browser update, `reason` value is `browser_update` and not `update` so data is erased ?

**Comment by ylecuyer** [comment] 2020-01-31 17:52
Yes @ajoah you're right ! thanks for the investigation I didn't get that the extension gets reinstalled on browser update but now that I see it, it seems logical.

I have made a fix here #25 I hope you can review it and then I will be able to push an update that will fix all the trouble :)

**Comment by ylecuyer** [comment] 2020-02-02 13:22
Eventually, this bug has been fixed in the 0.5 version :)

**Closed as completed by ylecuyer** 2020-02-02 13:22 UTC
